theme: jekyll-theme-minimal
title: Prof. Jacob
description: Jacob is currently working as assistant professor at Govt. Engineering College Idukki, Kerala. He has over 8 years of industry experience mostly in the area of SoC/Computer Architecture and Power Management.
